apiVersion: engines.gizmodata.com/v1alpha1
kind: GizmoSQLServerCluster
metadata:
  labels:
    app.kubernetes.io/name: gizmosql-operator
    app.kubernetes.io/managed-by: kustomize
  name: gizmosqlservercluster-sample
spec:
  # TODO(user): Add fields here
