{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: gizmosql-operator
    name: gizmosql-operator-gizmosqlservercluster-admin-role
rules:
    - apiGroups:
        - engines.gizmodata.com
      resources:
        - gizmosqlserverclusters
      verbs:
        - '*'
    - apiGroups:
        - engines.gizmodata.com
      resources:
        - gizmosqlserverclusters/status
      verbs:
        - get
{{- end }}
